import { NavBar } from '@/components/NavBar/NavBar';
import { TaskProvider } from '@/context/TasksContext';
import { Inter } from 'next/font/google';
import { Toaster } from './Toaster';

import './globals.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App Demo',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TaskProvider>
          <NavBar />
          <div className="bg-gray-900 text-white h-[calc(100vh-4rem)]">
            <main className='h-5/6 px-28 py-10'>
              {children}
            </main>
          </div>
          <Toaster />
        </TaskProvider>
      </body>
    </html>
  )
}
